name: Notebook Test Workflow

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        pip install jupyter nbconvert

    - name: Find and run notebooks
      run: |
        source venv/bin/activate
        FAILED_NOTEBOOKS=()
        for notebook in $(find . -name "*.ipynb"); do
          echo "Running $notebook"
          if ! jupyter nbconvert --to notebook --execute "$notebook" --output "$notebook"; then
            FAILED_NOTEBOOKS+=("$notebook")
          fi
        done
        if [ ${#FAILED_NOTEBOOKS[@]} -ne 0 ]; then
          echo "The following notebooks failed to execute:"
          for nb in "${FAILED_NOTEBOOKS[@]}"; do
            echo "$nb"
          done
          exit 1
        fi
